name: terminal-ui-dev

services:
  terminal-ui:
    image: ghcr.io/homeslands/terminal-service-ui:dev
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5178"] # TCP check on port 5178
      interval: 10s # Increase interval between health checks
      timeout: 10s # Increase timeout for slower responses
      retries: 5
    restart: unless-stopped
    ports:
      - "5178:5178"

networks:
  default:
    external: true
    name: scoobydoo
