import {
  Archive,
  ChartColumn,
  ClipboardList,
  CookingPot,
  Grid2x2,
  History,
  Printer,
  Receipt,
  // ShoppingCart,
  Store,
  Gift,
  MonitorCog,
  Users,
  TicketCheck,
  CoinsIcon,
  Utensils,
  CalendarClock,
} from 'lucide-react'

import type { ISidebarRoute } from '@/types'
import { ROUTE, Role } from '@/constants'
import { Permission } from '@/constants/sidebar-permission'

export const sidebarRoutes: ISidebarRoute[] = [
  {
    title: 'sidebar.overview',
    path: ROUTE.OVERVIEW,
    permission: Permission.OVERVIEW,
    icon: ChartColumn,
  },
  {
    title: 'sidebar.orderForCustomer',
    path: ROUTE.STAFF_MENU,
    icon: Utensils,
    permission: Permission.STAFF_MENU,
  },
  {
    title: 'sidebar.giftCardMenu',
    path: ROUTE.STAFF_GIFT_CARD_MENU,
    icon: TicketCheck,
    permission: Permission.CARD_MENU,
  },
  // {
  //   title: 'sidebar.deliveryManagement',
  //   path: ROUTE.STAFF_DELIVERY_MANAGEMENT,
  //   icon: ShoppingCart,
  //   permission: Permission.DELIVERY_MANAGEMENT,
  //   notificationCount: 0,
  // },
  {
    title: 'sidebar.chefOrderManagement',
    path: ROUTE.STAFF_CHEF_ORDER,
    icon: CookingPot,
    permission: Permission.CHEF_ORDER_MANAGEMENT,
    notificationCount: 0,
  },
  {
    title: 'sidebar.invoiceAreaManagement',
    path: ROUTE.STAFF_INVOICE_AREA_MANAGEMENT,
    icon: Printer,
    permission: Permission.BRANCH_MANAGEMENT,
  },
  {
    title: 'sidebar.cardOrderManagement',
    path: ROUTE.STAFF_CARD_ORDER_MANAGEMENT,
    icon: CoinsIcon,
    permission: Permission.CARD_ORDER_MANAGEMENT,
    notificationCount: 0,
  },
  {
    title: 'sidebar.orderManagement',
    path: ROUTE.STAFF_ORDER_MANAGEMENT,
    icon: Archive,
    permission: Permission.ORDER_MANAGEMENT,
    notificationCount: 0,
  },
  {
    title: 'sidebar.tableManagement',
    path: ROUTE.STAFF_TABLE_MANAGEMENT,
    icon: Grid2x2,
    permission: Permission.TABLE_MANAGEMENT,
  },
  {
    // Role-gated (no scope permission): visible to all booking-management roles.
    title: 'sidebar.tableBooking',
    path: ROUTE.STAFF_TABLE_BOOKING,
    icon: CalendarClock,
    allowedRoles: [
      Role.SUPER_ADMIN,
      Role.ADMIN,
      Role.MANAGER,
      Role.STAFF,
      Role.CASHIER,
      Role.TELESALE,
    ],
  },
  {
    title: 'sidebar.menuAndProductManagement',
    path: ROUTE.STAFF_MENU_AND_PRODUCT_MANAGEMENT,
    icon: ClipboardList,
    permission: Permission.MENU_MANAGEMENT,
  },
  // {
  //   title: 'sidebar.dishManagement',
  //   path: ROUTE.STAFF_PRODUCT_MANAGEMENT,
  //   icon: CookingPot,
  //   permission: Permission.PRODUCT_MANAGEMENT,
  // },
  {
    title: 'sidebar.customerAndMarketingManagement',
    path: ROUTE.STAFF_CUSTOMER_AND_MARKETING_MANAGEMENT,
    icon: Users,
    permission: Permission.CUSTOMER_MANAGEMENT,
    notificationCount: 0,
  },
  {
    title: 'sidebar.userManagement',
    path: ROUTE.STAFF_USER_MANAGEMENT,
    icon: Users,
    permission: Permission.EMPLOYEE_MANAGEMENT,
  },
  {
    // Role-gated (no scope permission): BE chưa cấp Permission.STAFF_SHIFT,
    // và CASHIER cần thấy mục này để mở/đóng ca của mình.
    title: 'sidebar.workShiftManagement',
    path: ROUTE.SYSTEM_WORK_SHIFTS,
    icon: ClipboardList,
    allowedRoles: [Role.SUPER_ADMIN, Role.ADMIN, Role.MANAGER, Role.CASHIER],
  },
  // {
  //   title: 'sidebar.customerGroupManagement',
  //   path: ROUTE.STAFF_CUSTOMER_GROUP_MANAGEMENT,
  //   icon: Users,
  //   permission: Permission.CUSTOMER_MANAGEMENT,
  // },
  {
    title: 'sidebar.branchManagement',
    path: ROUTE.STAFF_BRANCH_AND_SYSTEM_MANAGEMENT,
    icon: Store,
    permission: Permission.BRANCH_MANAGEMENT,
  },
  {
    title: 'sidebar.systemManagement',
    path: ROUTE.STAFF_SYSTEM_MANAGEMENT,
    icon: MonitorCog,
    permission: Permission.ROLE_MANAGEMENT,
  },
  // {
  //   title: 'sidebar.chefAreaManagement',
  //   path: ROUTE.STAFF_CHEF_AREA_MANAGEMENT,
  //   icon: ChefHat,
  //   permission: Permission.CHEF_AREA_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.staticPageManagement',
  //   path: ROUTE.STAFF_STATIC_PAGE,
  //   icon: FileChartColumnIncreasing,
  //   permission: Permission.PAGE_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.logManagement',
  //   path: ROUTE.STAFF_LOG_MANAGEMENT,
  //   icon: FileChartColumnIncreasing,
  //   permission: Permission.LOG_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.bankConfig',
  //   path: ROUTE.STAFF_BANK_CONFIG,
  //   icon: Banknote,
  //   permission: Permission.BANK_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.config',
  //   path: ROUTE.STAFF_CONFIG,
  //   icon: Bolt,
  //   permission: Permission.CONFIG_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.voucher',
  //   path: ROUTE.STAFF_VOUCHER_GROUP,
  //   icon: Ticket,
  //   permission: Permission.VOUCHER_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.promotion',
  //   path: ROUTE.STAFF_PROMOTION,
  //   icon: Tag,
  //   permission: Permission.PROMOTION_MANAGEMENT,
  // },
  {
    title: 'sidebar.giftCardManagement',
    path: ROUTE.STAFF_GIFT_CARD,
    icon: Gift,
    permission: Permission.CARD_MANAGEMENT,
  },
  // {
  //   title: 'sidebar.giftCardFeatureFlag',
  //   path: ROUTE.STAFF_GIFT_CARD_FEATURE_FLAG,
  //   icon: LockOpen,
  //   permission: Permission.BANNER_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.coinPolicy',
  //   path: ROUTE.STAFF_COIN_POLICY,
  //   icon: ShieldCheckIcon,
  //   permission: Permission.BANNER_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.systemLockManagement',
  //   path: ROUTE.STAFF_SYSTEM_LOCK_MANAGEMENT,
  //   icon: LockOpen,
  //   permission: Permission.BANNER_MANAGEMENT,
  // },
  // {
  //   title: 'sidebar.banner',
  //   path: ROUTE.STAFF_BANNER,
  //   icon: Newspaper,
  //   permission: Permission.BANNER_MANAGEMENT,
  // },
  {
    title: 'sidebar.vatManagement',
    path: ROUTE.STAFF_VAT_REQUEST,
    icon: Receipt,
    permission: Permission.VAT_MANAGEMENT,
  },
  {
    title: 'sidebar.auditLog',
    path: ROUTE.STAFF_AUDIT_LOG,
    icon: History,
    permission: Permission.AUDIT_LOG_MANAGEMENT,
  },
  {
    title: 'sidebar.clientView',
    path: ROUTE.STAFF_CUSTOMER_DISPLAY,
    icon: Users,
    permission: Permission.CLIENT_VIEW,
  },
]
