export enum FooterSection {
    BUSINESS_NAME = 'THE TERMINAL',
    TAX_CODE = '0319568608',
    ISSUED_ON = '2026-05-27',
    ORDER_INSTRUCTIONS = 'ORDER_INSTRUCTIONS',
    PAYMENT_INSTRUCTIONS = 'PAYMENT_INSTRUCTIONS',
    CONTACT = 'CONTACT',
    START_YEAR = 2026,
}